FROM nvidia/cuda:12.3.2-runtime-ubuntu20.04
# FROM nvidia/cuda:11.2.2-runtime-ubuntu20.04

RUN apt-get -y update \
    && apt-get install -y software-properties-common \
    && apt-get -y update \
    && add-apt-repository universe \
    && apt-get -y update \
    && apt-get -y install python3 python3-pip zbar-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt  --default-timeout=100
EXPOSE 5000
